[package]
name = "yew-flowchartjs-preview"
publish = false
version = "0.1.0"
authors = ["Aster <192607617@qq.com>"]
license = "MPL-2.0"
edition = "2018"

[dependencies]
yew = "0.17"
yew-flowchartjs = {version = "0.1", path = "../yew-flowchartjs" }

[dev-dependencies]


[features]
default = []
